# Generated by Django 5.1.1 on 2025-11-16 10:15

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentprofile",
            name="about",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="open_to_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="talent_profile_pic/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpeg", "jpg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="social",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
