# Generated by Django 5.1.1 on 2025-11-05 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpreference",
            name="job_types",
            field=models.CharField(
                choices=[
                    ("Full_time", "FULL_TIME"),
                    ("Part_time", "PART_TIME"),
                    ("Remote", "Remote"),
                    ("Open to all", "OPEN_TO_ALL"),
                ],
                default="Open to all",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="talentprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talentprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
