# Generated by Django 5.1.1 on 2025-11-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_jobpreference_job_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full_time", "FULL_TIME"),
                            ("Part_time", "PART_TIME"),
                            ("Remote", "Remote"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, default="INR", max_length=10),
                ),
                ("benefits", models.CharField(blank=True, max_length=500)),
                ("job_description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Internship", "Internship"),
                            ("Entry Level", "Entry Level"),
                            ("Mid Level", "Mid Level"),
                            ("Senior Level", "Senior Level"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "apply_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("job_role", models.ManyToManyField(to="accounts.jobtitle")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.location",
                    ),
                ),
                ("needed_skills", models.ManyToManyField(to="accounts.skill")),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.recruiterprofile",
                    ),
                ),
            ],
        ),
    ]
