# Generated by Django 5.1.1 on 2025-11-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_talentprofile_about_talentprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentprofile",
            name="social",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
