# Generated by Django 5.1.1 on 2025-11-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_jobtitle_jobtype_location_skill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentprofile",
            name="looking_for_locations",
        ),
        migrations.RemoveField(
            model_name="talentprofile",
            name="looking_for_titles",
        ),
        migrations.RemoveField(
            model_name="talentprofile",
            name="looking_for_types",
        ),
    ]
