# Generated by Django 5.1.1 on 2025-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_jobcontent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobTitle",
            new_name="JobRole",
        ),
    ]
