# Generated by Django 5.1.1 on 2025-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_talentprofile_looking_for_locations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpreference",
            name="job_types",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="JobType",
        ),
        migrations.AddField(
            model_name="jobpreference",
            name="job_types",
            field=models.CharField(
                choices=[
                    ("Full_time", "FULL_TIME"),
                    ("Part_time", "PART_TIME"),
                    ("Remote", "Remote"),
                    ("Open to all", "OPEN_TO_ALL"),
                ],
                default="OPEN_TO_ALL",
                max_length=20,
            ),
        ),
    ]
